### ISSUE TITLE
User submission workflow

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/countermapland#102]
As discussed, improve user submission flow:

- [x] Improved error message feedback loop
- [x] speed up submission time
- [x] add a wheel or other indication that the submission is still being processed

**Comment by writerly03** [comment]
Check that all relevant issues in #57 have been resolved

**Comment by tripledoublev** [comment]
I improved the submission workflow. It should be faster. Tell the user if the staticman instance in non-responsibe and show that data is being submitted with loading animation

- 6c81e97d0eb536769ffcee20dfa791cf23ce9fbf

- 34672d6248070b905d3a68b16c090966a2585ad7

- bc217cfcd8da88e3e51fb1a6ec58e02ffe416039
