### ISSUE TITLE
countermonument pop-up wireframe

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/countermapland#119]

**Comment by writerly03** [comment]
@inglenet can you double check that the countermonument wireframes has all of the required fields?

Otherwise, @tripledoublev this is the wireframe for displaying the countermonuments on the map

**Comment by inglenet** [comment]
@tripledoublev updated and tagged you for some feedback in Figma

**Comment by writerly03** [comment]
Waiting on usable data to implement this component.

**Comment by writerly03** [comment]
Wireframe has been implemented for phase I
