### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/countermapland#138]

**Comment by writerly03** [comment]
Dana to create a contact and volunteer form using Google Forms. Vincent to embed them as iframes on the site as a temp contact solution

**Comment by danasalama** [comment]
@tripledoublev @writerly03 I made a google form + added "volunteer" under "This is an option related to..." - I think this is more streamlined. We can use this form in both instances. https://forms.gle/5XzivJVuAUTYSWZe7

**Comment by writerly03** [comment]
@danasalama can you make Vincent a collaborator on the form? He needs this to be able to easily grab the html for the iframe embed. (You can do this under the three dot menu and 'add collaborators'.) Thanks!
