### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/countermapland#141]

**Comment by writerly03** [comment]
Change the countermap logo to this one: https://drive.google.com/drive/u/0/folders/1M9D8zCN38e37FFWe1Teks5_e07jjyhKk

**Comment by tripledoublev** [comment]
I added the logo and will close this issue. 
I think it is worth noting that since this logo is made of text, it might be better in the future to simply have it as a text header/ H1 (as opposed to SVG).
