### ISSUE TITLE
Include all data fields on beta test

### ISSUE THREAD

**Issue by danasalama** [hyphacoop/countermapland#47]
Can we include all data fields, even if they don't pertain to military memorials on the beta version? I think it is important to set out/ represent our intentions at this stage.

**Comment by tripledoublev** [comment]
I understand the intent but I believe this makes it a tricky implementation and suboptimal User Experience.
I can add them to the prototype but what purpose do they serve if it leads to nowhere and is in fact 'empty'. 
How do you implement something that does not exist yet?
Something to discuss during today's meeting.

**Comment by writerly03** [comment]
Have agreed to do this; @tripledoublev to add

**Comment by writerly03** [comment]
Add disclaimer about it being a prototype

**Comment by writerly03** [comment]
@inglenet can you update the search wireframe so it includes all of the fields from the momument index? e.g.

NAME 1
NAME 2
Latitude
Longitude
Location ( not included in catalogue)
STREET ADDRESS
IMAGE 1, IMAGE 2/photo
PLAQUE/ MARKER TEXT / inscription

DESCRIPTION/ background
ARTIST/ CREATOR/created_by (Note: this is mostly blank in the MM dataset)
AGENCIES SPONSORING/ MANAGING THE SITE/caretaker_e
OBJECT TYPE/ type

</div></b>
