### ISSUE TITLE
countermonuments to be represented/ tested

### ISSUE THREAD

**Issue by danasalama** [hyphacoop/countermapland#48]
Can we include some countermonument data on the beta test? I added entried in the Monument Index.

**Comment by writerly03** [comment]
See related issue #49

**Comment by writerly03** [comment]
- Need to create documentation for how to review the user submissions so Dana can add countermonuments

**Comment by writerly03** [comment]
Decision made to add countermonument data to map via spreadsheet versus completing the workflow.

@danasalama to send a cleaned up version of the sheet to Vincent in the next week or so.

**Comment by tripledoublev** [comment]
Countermonuments data was added to the map this morning

**Comment by writerly03** [comment]
@tripledoublev has this update been pushed to the website? I can't filter for counter monuments yet under the tools. I know we're still missing data but just checking

**Comment by tripledoublev** [comment]
I need to update the filters to account for the countermonuments data

**Comment by writerly03** [comment]
@tripledoublev Dana has added all of the images to Cloudinary: https://docs.google.com/spreadsheets/d/1JFv0QwwGEGr3TR2Ruf3C0R9axDJ2cVAYJUJg-953UaE/edit#gid=0
