### ISSUE TITLE
Wireframes V1

### ISSUE THREAD

**Issue by writerly03** [hyphacoop/countermapland#5]
Produce revised wireframes based on the priorities and themes surfaced in the co-design and optimizes for key actions taken on the website

**Comment by writerly03** [comment]
Link to wireframes https://www.figma.com/file/3WKET00QeSSLK75ANxUJFT/countermap.land?type=design&node-id=11-363&mode=design

**Comment by writerly03** [comment]
**Wireframes List**

- [ ] Welcome page (multi-modalities)
- [ ] Homepage - Map view
- [ ] Homepage - 
- [ ] Search> Filters>Labels
- [ ] Monument/Countermonument submissions
- [ ] Mounument/Countermonument marker pop-up
- [ ] About page
- [ ] Project page
- [ ] Research page
- [ ] Contact page

**Comment by writerly03** [comment]
**To do**

- [ ] Move asterisk to the front of '*countermap'
- [ ] align tools side bar labels with data available in the current military monuments set (i.e. gesture, material etc is not available so needs to be taken out)
- [ ] Update submit-sidebar copy with

**Comment by inglenet** [comment]
- [ ] update icons (media types, drop down, arrows)
- [ ] search list sidebar
- [ ] search drop-down/label elements
- [ ] adding tags/fields to submissions

**Comment by writerly03** [comment]
Name
Location ( not included in catalogue)
STREET ADDRESS
IMAGE 1, IMAGE 2/photo
PLAQUE/ MARKER TEXT / inscription


DESCRIPTION/ background
ARTIST/ CREATOR/created_by 
Manager
OBJECT TYPE/ type

**Comment by writerly03** [comment]
@inglenet here are the fields to include on the submission form in the 'add more information' section:

Year	
Artist
Agencies sponsoring 
Monument inscription 	
Subjects represented 		
Honorees	
Object type (e.g. stele, plaque, cairn)		
Material		
Area 
Height (m) 		
Width 		
Depth 		
Staging tactics 		
Gestures 

Source (not sure what this means or why it's pulled out)
