### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by danasalama** [hyphacoop/countermapland#50]
Two of the icons don't feel straightforward/ intuitive. (We can also tease this out in user testing).

The first in the asterisk that leads to "add a monument"--would a "plus sign" make more sense here? 
The second is the filter button - it looks like a menu. 

I wonder if these buttons can be located closer together.

**Comment by inglenet** [comment]
thanks Dana! agree that the difference between menu and filter could be a bit clearer. let's see how users respond to these and then make changes. either way, I've added some alternative button options for adding a countermonument in Figma.

**Comment by writerly03** [comment]
After the user testing session, we're suggesting the following icons changes:

- [x] Leave asterisk icon as-is, but it make it larger. Reason being that this is part of the visual iconography of the site 
- [x] Make map +/- smaller and relocate so it's not between the map switcher and the add a monument
- [x] Consider re-working map switcher;[ check feedback](https://docs.google.com/document/d/1wKU1FOcw4RXxVqqed_qXO6cIuao9hXkbyAnqGvuf2nA/edit) for details 
- [x] Change the icon for the filter/search to something more connected to search or filtering
- [x] Make menu icon bigger

**Comment by inglenet** [comment]
- [x] swapping out the asterisk for pin + asterisk on the add a countermonument button
