### ISSUE TITLE
Sidebar info

### ISSUE THREAD

**Issue by danasalama** [hyphacoop/countermapland#51]
- Place Indigenous name/ territory above colonial name 
- Can we somehow indicate that the description was not written by us? I don't want to look like we're parroting the state.
- Any way to click on images to enlarge them?

**Comment by tripledoublev** [comment]
I placed `Territories` above `municipality`.
d8f156595e022b00b9877c3e762f4f82668aa827
For description, it would be a matter of adding a text disclamer to indicate it was not written by us.
As for the enlarged images, I could see it being a modal for full screen view.
Some design input from @inglenet  would be appreciated on that front.

**Comment by writerly03** [comment]
Closing as we have added the disclaimer text, moved the location of territories and the enlarged images has been taken up in issue #63
