### ISSUE TITLE
User submission workflow issues

### ISSUE THREAD

**Issue by danasalama** [hyphacoop/countermapland#57]
1. When I hovered off the sidebar, it disappeared and my data was lost
2. Add a place for people to submit URLs/ data sources
3. Do we need to add a field for image URLs? Is that how images are currently appearing?
4. After I upload an image, I can't tell whether it has worked or not.
5. Object type should have existing fields (see Monument Index)
6. Material should have existing fields (see Monument Index)
7. Staging tactics should have existing fields (see Monument Index)
8. Gestures should have existing fields 
9. Year is unclear - this needs to be broken down into year dedicated, year constructed, year removed --even if these are eventually combined in the search function 
10. I think the difference between "subject" and "honoree" will be unclear to users --maybe instead of "subject" we add "community implicated?" Not sure if that is clearer.
11. if there are multiple entries, will separating these out with a comma work? For example - mutliple honorees or multiple materials?

**Comment by tripledoublev** [comment]
Submission workflow isnt complete yet so I will revisit this issue when I finish implementing the feature

**Comment by writerly03** [comment]
For 2-3; we're going to push the function to a later phase once we have more discussion around ensuring ppl are only uploading things they have copyright to etc. 

1 & 4 - bug fixes

For points 5-8 above, you can take the data from the categories tab here: https://docs.google.com/spreadsheets/d/1UC2iasmn9WGxp5PPctfxBBUTJS8y1LbFurlulLOhcWI/edit#gid=496898629

@inglenet 9-11 are for you to consider in the redesign of the form

**Comment by writerly03** [comment]
See #101 and #102

**Comment by writerly03** [comment]
Form has been redesigned. Other aspects of the user submission flow will remain unresolved until the next phase of development.
