### ISSUE TITLE
Landing page?

### ISSUE THREAD

**Issue by danasalama** [hyphacoop/countermapland#59]
How are people initially introduced to the project/ its conceptual underpinnings? I know that Sarah had drafted something - will it appear in this version of the site?

**Comment by tripledoublev** [comment]
@danasalama, here is the welcome page
https://hyphacoop.github.io/countermapland/

**Comment by tripledoublev** [comment]
I still have two 'types' of 'welcoming prompts' to implement based on Sarah's wireframes
